development:
  adapter: postgresql
  encoding: unicode
  database: hoc_development
  pool: 5
  username: hoc
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: hoc_test
  pool: 5
  username: hoc
  password:
